from typing import TYPE_CHECKING

from alembic import command
from alembic.config import Config

if TYPE_CHECKING:
    import pytest


def test_initial_migration_renders_reproducible_postgres_sql(
    capsys: pytest.CaptureFixture[str],
) -> None:
    command.upgrade(Config("alembic.ini"), "head", sql=True)

    migration_sql = capsys.readouterr().out
    expected_snippets = (
        "CREATE SCHEMA IF NOT EXISTS reference",
        "CREATE SCHEMA IF NOT EXISTS market",
        "CREATE SCHEMA IF NOT EXISTS operations",
        "CREATE TABLE reference.instrument",
        "CREATE TABLE operations.raw_api_response",
        "CREATE TABLE market.quote",
        "CREATE TABLE market.market_bar",
        "CONSTRAINT uq_market_bar_identity UNIQUE",
        "CONSTRAINT uq_market_bar_version UNIQUE",
        "CREATE UNIQUE INDEX uq_market_bar_current",
        "CONSTRAINT ck_market_bar_finality",
        "CONSTRAINT ck_market_bar_confirmation",
        "CONSTRAINT ck_market_bar_validity",
        "CREATE TABLE reference.market_calendar",
        "CONSTRAINT ck_market_calendar_session_window",
        "CREATE UNIQUE INDEX uq_market_calendar_current",
        "CREATE TABLE operations.scheduled_job_run",
        "CONSTRAINT uq_scheduled_job_execution UNIQUE",
        "CONSTRAINT ck_scheduled_job_state",
        "CREATE TABLE market.corporate_action",
        "CONSTRAINT uq_corporate_action_version UNIQUE",
        "CONSTRAINT uq_corporate_action_source_event UNIQUE",
        "CREATE UNIQUE INDEX uq_corporate_action_current",
        "CONSTRAINT ck_corporate_action_type",
        "CONSTRAINT ck_corporate_action_lifecycle",
        "CONSTRAINT ck_corporate_action_quality",
        "CONSTRAINT ck_corporate_action_time_precision",
        "CONSTRAINT ck_corporate_action_share_multiplier",
        "CONSTRAINT ck_corporate_action_amounts",
        "CONSTRAINT ck_corporate_action_version",
        "CONSTRAINT ck_corporate_action_validity",
        "CREATE TABLE market.adjustment_dataset",
        "CONSTRAINT ck_adjustment_dataset_method",
        "CONSTRAINT ck_adjustment_dataset_status",
        "CREATE UNIQUE INDEX uq_adjustment_dataset_inputs",
        "CREATE TABLE market.adjustment_dataset_action",
        "CONSTRAINT ck_adjustment_dataset_action_factors",
        "CREATE TABLE market.adjusted_market_bar",
        "CONSTRAINT uq_adjusted_market_bar_date UNIQUE",
        "CONSTRAINT ck_adjusted_market_bar_factors",
        "CREATE TABLE market.minute_bar",
        "CONSTRAINT uq_minute_bar_version UNIQUE",
        "CREATE UNIQUE INDEX uq_minute_bar_current",
        "CONSTRAINT ck_minute_bar_prices",
        "CONSTRAINT ck_minute_bar_amounts",
        "CONSTRAINT ck_minute_bar_finality",
        "CONSTRAINT ck_minute_bar_confirmation",
        "CONSTRAINT ck_minute_bar_version",
        "CONSTRAINT ck_minute_bar_validity",
        "CREATE TABLE fundamental.financial_report",
        "CONSTRAINT uq_financial_report_version UNIQUE",
        "CONSTRAINT uq_financial_report_receipt UNIQUE",
        "CREATE UNIQUE INDEX uq_financial_report_current",
        "CONSTRAINT ck_financial_report_reprt_code",
        "CONSTRAINT ck_financial_report_fs_div",
        "CONSTRAINT ck_financial_report_year",
        "CONSTRAINT ck_financial_report_version",
        "CONSTRAINT ck_financial_report_validity",
        "CREATE TABLE fundamental.financial_statement_line",
        "CONSTRAINT uq_financial_statement_line_seq UNIQUE",
        "CONSTRAINT ck_financial_statement_line_seq",
        "CONSTRAINT ck_financial_statement_line_sj_div",
        "CREATE TABLE reference.listed_share_count",
        "CONSTRAINT uq_listed_share_count_version UNIQUE",
        "CREATE UNIQUE INDEX uq_listed_share_count_current",
        "CONSTRAINT ck_listed_share_count_positive",
        "CONSTRAINT ck_listed_share_count_version",
        "CONSTRAINT ck_listed_share_count_validity",
        "CREATE TABLE market.investor_flow",
        "CONSTRAINT uq_investor_flow_version UNIQUE",
        "CREATE UNIQUE INDEX uq_investor_flow_current",
        "CONSTRAINT ck_investor_flow_version",
        "CONSTRAINT ck_investor_flow_validity",
        "CREATE TABLE fundamental.disclosure",
        "CONSTRAINT uq_disclosure_receipt UNIQUE",
        "CONSTRAINT ck_disclosure_type",
    )
    for snippet in expected_snippets:
        assert snippet in migration_sql
